### ISSUE TITLE
Iterable class in collections depreciated in python 3.10 - pyphot dependency

### ISSUE THREAD

**Issue by vickyscowcroft** [mfouesneau/dustapprox#1]
Hello,
Found an issue when using dustapprox with python 3.10. It can't be imported because of the pyphot dependency containing depreciated Iterable class

I've fixed it using the edit listed here: https://github.com/mfouesneau/pyphot/issues/47#issue-1317813250

Wasn't sure if you knew it was affecting dustapprox as well as pyphot. 

Thanks
Vicky

**Comment by mfouesneau** [comment]
I did not know thanks

**Comment by mfouesneau** [comment]
9486101 adds tests for python 3.10

**Comment by mfouesneau** [comment]
Fixed in pyphot 1.4.4
