### ISSUE TITLE
Help with file "kurucs_gaiaedr3_small_a0_grid.csv"

### ISSUE THREAD

**Issue by Antonio19-jpg** [mfouesneau/dustapprox#3]
Hi, is it possible to have the file used in the Quick Start example ("kurucs_gaiaedr3_small_a0_grid.csv")? Just to see how it is formatted. 
Thank you

**Comment by mfouesneau** [comment]
It is in the repository: [docs/models/precomputed/kurucs_gaiaedr3_small_a0_grid.csv](https://github.com/mfouesneau/dustapprox/blob/main/docs/models/precomputed/kurucs_gaiaedr3_small_a0_grid.csv)
