### ISSUE TITLE
Can not access dustapprox.literature.edr3.edr3_ext.from_bprp() method

### ISSUE THREAD

**Issue by Gabriel-p** [mfouesneau/dustapprox#4]
I'm trying to extract excinction coefficients with the [edr3.edr3_ext.from_bprp()](https://mfouesneau.github.io/dustapprox/dustapprox.literature.html#dustapprox.literature.edr3.edr3_ext) method but I can't seem to get it to work.

Here's my code:

```
import dustapprox

BPRP = np.arange(0, 5, .1)

model = dustapprox.literature.edr3.edr3_ext()
model.from_bprp("BP", BPRP, 1)

*** KeyError: 'BP'
```

I've tried other ways of importing he module but it just won't work. What am I doing wrong here?

**Comment by mfouesneau** [comment]
Indeed, sorry the documentation is incorrect, you need to use `kBP` instead of `BP`
```python
In []: model.from_bprp('kBP', BPRP, 1.)
Out[]: 
array([1.13318978, 1.12498006, 1.11624044, 1.1070552 , 1.09750856,
       1.0876848 , 1.07766816, 1.06754289, 1.05739325, 1.04730349,
       1.03735786, 1.02764062, 1.01823601, 1.00922829, 1.00070171,
       0.99274053, 0.98542899, 0.97885135, 0.97309186, 0.96823478,
       0.96436435, 0.96156484, 0.95992048, 0.95951554, 0.96043426,
       0.96276091, 0.96657972, 0.97197496, 0.97903088, 0.98783172,
       0.99846175, 1.01100521, 1.02554636, 1.04216944, 1.06095872,
       1.08199844, 1.10537286, 1.13116622, 1.15946279, 1.19034681,
       1.22390254, 1.26021423, 1.29936613, 1.34144249, 1.38652757,
       1.43470561, 1.48606088, 1.54067762, 1.59864009, 1.66003254])
```

**Comment by Gabriel-p** [comment]
Thank you very much, I got it working now.

I'd like to ask you a follow up question if you don't mind. I'm testing a few extinction-related packages and I find the differences to be rather large.

The image below shows a comparision of the packages: [dust_extinction](https://github.com/karllark/dust_extinction) (I used the O'Donell model); the coefficients in the article [Gaia Collaboration (2018)](https://ui.adsabs.harvard.edu/abs/2018A%26A...616A..10G), [extinction_coefficient](https://github.com/vnohhf/extinction_coefficient), and this package (code is below):

![Captura de pantalla de 2024-04-29 14 45 57](https://github.com/mfouesneau/dustapprox/assets/6054951/77f7f2cf-d342-435c-8406-fd35a49c4921)

Except for the O'donell model, the rest of the models are color (or Teff)-dependent. The region `BP-RP>3` is what strikes me as odd given how quickly the `E(BP-RP)`  value increases for the coefficients in Gaia Collaboration (2018) and this package.

Do these curves look reasonable to you or have I made a mistake?


```
import numpy as np
import matplotlib.pyplot as plt
import astropy.units as u
from dust_extinction.parameter_averages import O94
from extinction_coefficient import extinction_coefficient
from dustapprox.literature.edr3 import edr3_ext


def main():
    """ """
    # Define (BP-RP) range, Av, and Rv values
    BP_RP = np.arange(0, 5, 0.1)
    Av = 1
    Rv = 3.1

    # Coefficients from O'donell (1994) model
    ext_model = O94(Rv=Rv)
    ec_bp = ext_model(5182.58*u.AA)
    ec_rp = ext_model(7825.08*u.AA)
    A_BP = ec_bp * Av
    A_RP = ec_rp * Av
    E_BP_RP_o94 = A_BP - A_RP

    # Coefficients from Gaia Collaboration (2018)
    # https://ui.adsabs.harvard.edu/abs/2018A%26A...616A..10G
    ec_bp = gaia_collab_18(BP_RP, Av, 1)
    ec_rp = gaia_collab_18(BP_RP, Av, 2)
    A_BP = ec_bp * Av
    A_RP = ec_rp * Av
    E_BP_RP_gaia_18 = A_BP - A_RP

    # Coefficients from 'extinction_coefficient' (Zhang & Yuan, 2022).
    # https://github.com/vnohhf/extinction_coefficient
    EBV = Av / Rv
    ec_ZY = extinction_coefficient("BP-RP", EBV=EBV, BP_RP=list(BP_RP))
    E_BP_RP_gaia_ZY = ec_ZY * EBV

    # Coefficients from 'dustapprox'
    # https://github.com/mfouesneau/dustapprox
    model = edr3_ext()
    ec_bp = model.from_bprp("kBP", BP_RP, Av)
    ec_rp = model.from_bprp("kRP", BP_RP, Av)
    A_BP = ec_bp * Av
    A_RP = ec_rp * Av
    E_BP_RP_gaia_DA = A_BP - A_RP

    plt.suptitle("AV={:.1f}, Rv={:.1f} --> Av/RV=E(B-V)={:.2f}".format(Av, Rv, EBV))
    plt.subplot(121)
    plt.axhline(E_BP_RP_o94, c='r', label="dust_extinction (O94)")
    plt.plot(BP_RP, E_BP_RP_gaia_18, label="Gaia Collaboration (2018)")
    plt.plot(BP_RP, E_BP_RP_gaia_ZY, label="extinction_coefficient")
    plt.plot(BP_RP, E_BP_RP_gaia_DA, label="dustapprox")
    plt.legend()
    plt.xlabel("BP-RP")
    plt.ylabel("E(BP-RP)")
    plt.xlim(0, 3)
    plt.ylim(.3, .65)
    plt.subplot(122)
    plt.axhline(E_BP_RP_o94, c='r', label="dust_extinction (O94)")
    plt.plot(BP_RP, E_BP_RP_gaia_18, label="Gaia Collaboration (2018)")
    plt.plot(BP_RP, E_BP_RP_gaia_ZY, label="extinction_coefficient")
    plt.plot(BP_RP, E_BP_RP_gaia_DA, label="dustapprox")
    plt.legend()
    plt.xlabel("BP-RP")
    plt.show()


def gaia_collab_18(BP_RP, Av, i):
    """
    Gaia Collaboration (2018)
    https://ui.adsabs.harvard.edu/abs/2018A%26A...616A..10G
    """
    c1 = [0.9761, 1.1517, 0.6104]
    c2 = [-0.1704, -0.0871, -0.0170]
    c3 = [0.0086, -0.0333, -0.0026]
    c4 = [0.0011, 0.0173, -0.0017]
    c5 = [-0.0438, -0.0230, -0.0078]
    c6 = [0.0013, 0.0006, 0.00005]
    c7 = [0.0099, 0.0043, 0.0006]

    return c1[i] + c2[i]*BP_RP + c3[i]*BP_RP**2 + c4[i]*BP_RP**3 \
        + c5[i]*Av + c6[i]*Av**2 + c7[i]*BP_RP*Av


if __name__ == '__main__':
    main()
```

**Comment by mfouesneau** [comment]
First, all these polynomial relations are approximations to the effects of original extinction curves.  

Extinction curves implement by construction `E(B-V) = A(V) / R(V)`, and they adopt their definitions of V and B bands. These are parametric decisions. The curve applies to the spectra, not to the integrated photometric values.
Any E(BP-RP) not dependent on the intrinsic color of the source cannot be correct because the BP/RP passbands are so large that extinction affects the spectra differently throughout the band. We recall this in our documentation: https://mfouesneau.github.io/dustapprox//index-2.hires.png.

Here, `edr3_ext` implements the Gaia Collaboration equation without additional calibration. Although the offset seems suspicious (did you use the same flavor giant or main-sequence?), it is normal that they change as a function of intrinsic color. You can see that the `extinction_coefficient` curve typically "saturates"; a clipping comes from the curve definition.

Hence, using E(X-Y) ~ A0/R0 is prone to larger errors from all the above. Use a "stone of salt" here. 

We show some biases in our documentation when calculating extinction values correctly: https://mfouesneau.github.io/dustapprox//index-3.hires.png.

As mentioned here, Approximations must be taken with a grain of salt and understood. You cannot apply the calibration of one approximation to another, especially with R(X) relations and wide bands such as Gaia. 

I hope this helps

**Comment by Gabriel-p** [comment]
Thank you very much again @mfouesneau for the detailed explanation. I see now that the reccomended range for (BP-RP) is [below 2.5](https://www.cosmos.esa.int/web/gaia/edr3-extinction-law); in that range the curve does not blow up and is much more reasonable.

I plan on adding this BP-RP dependent curve as an alternative to the O'Donell model in my [ASteCA](https://asteca.readthedocs.io/en/latest/) package and what is still not entirely clear to me is the difference between the curve shown in [Gaia Collaboration 2018, Eq 1](https://ui.adsabs.harvard.edu/abs/2018A%26A...616A..10G) and the one used in this package. Is this one recommended over the other? I assume it is as it appears in [Gaia's own site](https://www.cosmos.esa.int/web/gaia/edr3-extinction-law)?

Using the 'main sequence' flavor there appears to be a significant offset between both curves:

![Figure_1](https://github.com/mfouesneau/dustapprox/assets/6054951/02db726a-aae6-4e5d-a981-761513ce9eba)

Finally, is the model in this package valid for Rv=3.1 exclusively?  Thank you for your patience in answering these questions!

**Comment by mfouesneau** [comment]
The Gaia collaboration is implemented as provided on their documents. They have two relations depending on being for giants or main sequence. This leads to strong differences for reasons I mentioned before.

These are approximations valid for specific assumptions. RV=3.1 is fixed for all available models at the moment. 

Variations of RV have significant effects on the integrated Gaia photometry predictions.

Any approximations must account for at least the temperature of the source, but metallicity can also have an impact. (Note that the Edr3 model expects the dust free colors)

**Comment by mfouesneau** [comment]
The reference you have for Gaia 2018 is Gaia dr2 with a different calibration of the photometry. This package implements a version for Gaia (e)Dr3

**Comment by Gabriel-p** [comment]
Thank you very much again Morgan, I hadn't realized the Gaia Collab 2018 reference was for DR2 photometry.
